name: Heart Disease Data Preprocessing

# Trigger workflow
on:
  push:
    branches: [ main, master ]
    paths:
      - 'heart.csv'
      - 'preprocessing/**'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn joblib matplotlib seaborn
    
    - name: Create directories
      run: |
        mkdir -p preprocessing/data/processed
    
    - name: Run automated preprocessing
      working-directory: ./preprocessing
      run: |
        python automate_Andre.py
    
    - name: Check processed files
      run: |
        echo "Checking processed files..."
        ls -la preprocessing/data/processed/
        
        echo "X_train.csv shape:"
        python -c "import pandas as pd; print(pd.read_csv('preprocessing/data/processed/X_train.csv').shape)"
        
        echo "X_test.csv shape:"
        python -c "import pandas as pd; print(pd.read_csv('preprocessing/data/processed/X_test.csv').shape)"
        
        echo "y_train.csv shape:"
        python -c "import pandas as pd; print(pd.read_csv('preprocessing/data/processed/y_train.csv').shape)"
        
        echo "y_test.csv shape:"
        python -c "import pandas as pd; print(pd.read_csv('preprocessing/data/processed/y_test.csv').shape)"
    
    - name: Upload processed data as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: processed-heart-data
        path: |
          preprocessing/data/processed/X_train.csv
          preprocessing/data/processed/X_test.csv
          preprocessing/data/processed/y_train.csv
          preprocessing/data/processed/y_test.csv
          preprocessing/data/processed/preprocessor.pkl
        retention-days: 30
    
    - name: Commit processed data (if on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add preprocessing/data/processed/
        git diff --staged --quiet || git commit -m "Auto-update processed data [skip ci]"
        git push